{% set version = "1.3.0" %}

package:
  name: hs_restclient
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hs_restclient/hs_restclient-{{ version }}.tar.gz
  sha256: 9f76428ba3c228e1d1239697f3ef0407cd81a9c3b68696f1880970e9389bf276

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - requests-toolbelt
    - oauthlib
    - requests-oauthlib

test:
  imports:
    - hs_restclient
    - hs_restclient.endpoints

about:
  home: https://github.com/hydroshare/hs_restclient
  license: BSD
  summary: 'HydroShare REST API client library'

extra:
  recipe-maintainers:
    - ocefpaf
