{% set version = "1.3.5" %}

package:
  name: hs_restclient
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hs_restclient/hs_restclient-{{ version }}.tar.gz
  sha256: 083f262f419316a5294a1d9a7a6fee5a73d59bb3d44b5aaf66f19c664e7e9ee1

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - requests-toolbelt
    - oauthlib
    - requests-oauthlib

test:
  imports:
    - hs_restclient
    - hs_restclient.endpoints

about:
  home: https://github.com/hydroshare/hs_restclient
  # https://github.com/hydroshare/hs_restclient/issues/107
  license: BSD
  summary: 'HydroShare REST API client library'

extra:
  recipe-maintainers:
    - ocefpaf
