{% set version = "1.3.3" %}

package:
  name: hs_restclient
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hs_restclient/hs_restclient-{{ version }}.tar.gz
  sha256: dfaae6e059d11a74887f8d27178aae5ddd87809d3ab70f44bdfe250af9f1b662

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - requests-toolbelt
    - oauthlib
    - requests-oauthlib

test:
  imports:
    - hs_restclient
    - hs_restclient.endpoints

about:
  home: https://github.com/hydroshare/hs_restclient
  # https://github.com/hydroshare/hs_restclient/issues/107
  license: BSD
  summary: 'HydroShare REST API client library'

extra:
  recipe-maintainers:
    - ocefpaf
