travis:
  secure:
    BINSTAR_TOKEN: cQFtd0JeLYLnHXsn5C6Lu7/8vraj5PStgr0aaMHopXgm4nnHo5quezfPxHpNcSyuwyp4LnTEB+QHJCJEFxWGEmoJxO+fzu7rKbuV/rdY81ld06bqGHC51O3T7YHdZOWhWi26bZyUWeSUKk0GNksIpZH3QRis36CHX9L3C5O/YAt4t8ZhimOcqjkSD0Sd0PJI4acUFZ4N4yFcY41NlIUPQRdN6JzXsSp9e4duA8+gx3v7zvOF+iG0X7VsRMZO/f0O9aPNZTI1sitHTLrhAS0LkT2255/8TRnzdv2dvQ6a2pkll6PItUQoVFJk6tio8CWvt99zyf6dE6ACCmB7iyfPrSBvUi2WNCJCS2JSiPSG7xREp/jgVu29YCDW3vfptAKS5fltmxlkHioNk41+gdS9XNzkU9TE11Pa1hsX+sLEZhZtIZoLhf3iu/LVNTeB6CN2SebJjpEQkugTiTBuMnMVB9I0YXLdbwdu1DGhArcwS0Zb8pB8AThq6TjDTr+K2YXNfyvbYZyEZpZw1PtazhKsk2jfV9SHRoekNxFaINkCVkBwzCsJiYNq/w4nvfj+r99Uqf/3HVAyY/7ShjsdiuHUFC7+T5tjYSCbQ1WWz+ewfvvy5KS0/0T5OJ6OmMFUJHt3aEhWK5Wd2QsJ4N5ogNJN9cn77dCLFrT5btUJLPKQWaE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
